#define BUZZER_PIN 12
#define LED_PIN  14
#define BACK_BUTTON_PIN 37
#define GO_BUTTON_PIN 5
#define UP_BUTTON_PIN 43
#define DOWN_BUTTON_PIN 4
#define DHT_PIN 36
#define DHTTYPE DHT11
#define SCREEN_WIDTH 32
#define SCREEN_HEIGHT 8
#define LED_COUNT SCREEN_WIDTH * SCREEN_HEIGHT
#define NTP_SERVER "ntp.ntsc.ac.cn"
#define TIME_ZONE_OFFSET_IN_SECONDS 8 * 3600
#define UPDATE_INTERVALMILLIS 60 * 60 * 1000
#define BILIILI_UID "504877841"